import { Masthead } from '@/components/masthead'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Margelo | Homepage</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head >

      <Masthead />
    </div >
  )
}

export default Home
