import { Aboutus } from '@/components/aboutus'
import { Masthead } from '@/components/masthead'
import { Skills } from '@/components/skills'
import { Members } from '@/types/member_types'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage<Members> = ({ members }) => (
  <div>
    <Head>
      <title>Margelo | Homepage</title>
      <meta name="description" content="Generated by create next app" />
    </Head >

    <Masthead />
    <Aboutus members={members} />
    <Skills />
  </div >
)

export default Home

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/members")
  const members = await res.json()

  return {
    props: { members: members.members }
  }
}

